name = "Academic Paper"
description = "A Zola theme for a blog-post-style website to facilitate scientific communication of your academic paper"
license = "MIT"
homepage = "https://github.com/aterenin/academic-paper"
min_version = "0.18.0"
demo = "https://aterenin.github.io/academic-paper"

[extra]
footer_text = "This website is built using [Zola](https://www.getzola.org) and the [Academic Paper](http://github.com/aterenin/academic-paper/) theme, which is [designed to last](https://jeffhuang.com/designed_to_last/)."

[author]
name = "Alexander Terenin"
homepage = "https://avt.im"